# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
use_frameworks!
target 'EnLista' do
	project 'EnLista.xcodeproj'
	pod 'FBSDKCoreKit', '9.2.0'
	pod 'FBSDKLoginKit', '9.2.0'
	pod 'FBSDKShareKit', '9.2.0'
	pod 'GoogleSignIn', '~> 5.0.2'
	pod 'GoogleUtilities', '~> 7.2.2'
	pod 'GoogleAnalytics', '3.20.0'
	pod 'OneSignalXCFramework', '3.11.2'
end